# Generated by Django 5.1.1 on 2024-09-06 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_upload_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='Company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='department', to='company.company'),
        ),
    ]
